### PR TITLE
Adding SLURM and Singularity

### PR DESCRIPTION
**Pull request by hoelzer**
I added the profiles and tested on our HPC. 

**Attention**: I also changed the container for plasflow from

`quay.io/biocontainers/plasflow:1.1.0--py35_0`

to

`nanozoo/plasflow:1.1.0--c85355d`

because I had issues pulling from quay.io. (which is a special security edge case others very likely dont have). 

I hope it's fine because it should be the same version of plasflow. 

I am testing the changes on one _Klebsiella_ sample right now....

### CODE REVIEW

**Comment by hoelzer** [comment]
```
[e7/260445] process > mask_regions_degen_wf:minimap2_degen (1) [100%] 1 of 1, cached: 1 ✔
[ab/f981e9] process > mask_regions_degen_wf:bedtools (1)       [100%] 1 of 1, cached: 1 ✔
[d2/fdf2df] process > mask_regions_degen_wf:plasflow_degen (1) [100%] 1 of 1, cached: 1 ✔
[e5/9f8dc0] process > identify_logo_wf:count_positions (1)     [100%] 1 of 1, cached: 1 ✔
[90/6a0b5a] process > identify_logo_wf:extract_sequence (1)    [100%] 1 of 1, cached: 1 ✔
[ab/6389fd] process > identify_logo_wf:plot_motifs (1)         [100%] 1 of 1, failed: 1 ✔
KP01_RKI (chromosome): N:18, W:2, S:4, M:6, K:3, R:90, Y:69, B:0, D:0, H:0, V:0
[ab/6389fd] NOTE: Process `identify_logo_wf:plot_motifs (1)` terminated with an error exit status (1) -- Error is ignored
```

**Comment by hoelzer** [comment]
Ah I think that is the problem:

```
cat work/ab/6389fde235b854c15f30dde2e119db/.command.log
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
Warning in install.packages("ggseqlogo") :
  'lib = "/usr/local/lib/R/site-library"' is not writable
Error in install.packages("ggseqlogo") : unable to install packages
Execution halted
```

so probably you are installing smt during the plot_motif process but this will fail on systems that are more "closed" like an HPC. Or it's an SIngularity problem.

**Comment by hoelzer** [comment]
I will try to add `install.packages("ggseqlogo")` directly to the ggplot2 nz container and see if this works

**Comment by hoelzer** [comment]
Alright, updating the container with the lib worked:

```
executor >  slurm (1)
[e7/260445] process > mask_regions_degen_wf:minimap2_degen (1) [100%] 1 of 1, cached: 1 ✔
[ab/f981e9] process > mask_regions_degen_wf:bedtools (1)       [100%] 1 of 1, cached: 1 ✔
[d2/fdf2df] process > mask_regions_degen_wf:plasflow_degen (1) [100%] 1 of 1, cached: 1 ✔
[e5/9f8dc0] process > identify_logo_wf:count_positions (1)     [100%] 1 of 1, cached: 1 ✔
[90/6a0b5a] process > identify_logo_wf:extract_sequence (1)    [100%] 1 of 1, cached: 1 ✔
[b8/21576a] process > identify_logo_wf:plot_motifs (1)         [100%] 1 of 1 ✔
KP01_RKI (chromosome): N:18, W:2, S:4, M:6, K:3, R:90, Y:69, B:0, D:0, H:0, V:0
```

**Comment by hoelzer** [comment]
Output I get:

image

**Comment by hoelzer** [comment]
From my site this can be merged, adding support for HPC w/ SLURM and SINGULARITY.

**Comment by hoelzer** [comment]
@replikation @maralohde can you shortly explain for me again how you detect these motifs? To then mask them?

**Comment by replikation** [comment]
@hoelzer good catch with the rplot. I need to build an appropriate container
can you rerun and resume the workflow with --frequency? Generates another plot for all positions

**Comment by maralohde** [comment]
> @replikation @maralohde can you shortly explain for me again how you detect these motifs? To then mask them?

@hoelzer In the first move the ambiguous positions are masked by IUPAC-code using samtools consensus. From these masked positions, we count +/- 5 positions and plot them.

**Comment by hoelzer** [comment]
> > @replikation @maralohde can you shortly explain for me again how you detect these motifs? To then mask them?
> 
> @hoelzer In the first move, the ambiguous positions are masked by IUPAC-code using samtools consensus. From the sum of all reads with this ambiguous position in one sample we plot the motif +/- 5 bases.

Alright. So in my case above, there are three ambiguous bases detected in the mapped reads: M, R, and Y. Now, you extract for all of these three cases the surrounding nucleotides and plot the motifs. Ok, got it. 

From your preprint 

RACG
CGTY

seems common for K. pneumoniae. So it's a bit different for me - but I also just ran only one rndm isolate for a first test.

**Comment by hoelzer** [comment]
adding `--frequency` fails... I am investigating why... 

[51/ad0039] process > identify_logo_wf:get_frequency (1)       [100%] 1 of 1, failed: 1 ✘

Command exit status:
  137

Maybe out of RAM? 

Ah yeah

slurmstepd-hpc-node03: error: Detected 1 oom-kill event(s) in StepId=2316838.batch. Some of your processes may have been killed by the cgroup out-of-memory handler.

adding some increase rule...

**Comment by replikation** [comment]
Yeah looks like ram might be an issue

**Comment by hoelzer** [comment]
Yep, added an auto-increase of RAM:

executor >  slurm (4)
[e7/260445] process > mask_regions_degen_wf:minimap2_degen (1) [100%] 1 of 1, cached: 1 ✔
[ab/f981e9] process > mask_regions_degen_wf:bedtools (1)       [100%] 1 of 1, cached: 1 ✔
[d2/fdf2df] process > mask_regions_degen_wf:plasflow_degen (1) [100%] 1 of 1, cached: 1 ✔
[e5/9f8dc0] process > identify_logo_wf:count_positions (1)     [100%] 1 of 1, cached: 1 ✔
[90/6a0b5a] process > identify_logo_wf:extract_sequence (1)    [100%] 1 of 1, cached: 1 ✔
[b8/21576a] process > identify_logo_wf:plot_motifs (1)         [100%] 1 of 1, cached: 1 ✔
[d7/133d1e] process > identify_logo_wf:get_frequency (1)       [100%] 3 of 3, failed: 2, retries: 2 ✔
[82/aa1ef4] process > identify_logo_wf:plot_frequency          [100%] 1 of 1 ✔
Completed at: 08-Nov-2023 13:47:48
Duration    : 14m 22s
CPU hours   : 2.8 (51.1% cached, 25.2% failed)
Succeeded   : 2
Cached      : 6
Failed      : 2

**Comment by hoelzer** [comment]
I also got now: 

image

**Comment by hoelzer** [comment]
How do I interpret this plot again : )

**Comment by hoelzer** [comment]
I still have a error running moe samples, probably increase RAM more. Will check after my meeting. Dont merge yet pls ;)

**Comment by replikation** [comment]
We wait until you give green light no worries

**Comment by hoelzer** [comment]
Ok, I think the incremental RAM increase solved the issue with the get_frequency process. I am running 20 Listeria samples. One is failing in

[3e/5ff788] process > identify_logo_wf:plot_motifs (3)          [100%] 20 of 20, cached: 19, failed: 1 ✔

and I dont know why:

```bash
ls work/3e/5ff788e6e2b394a6cf9e3932be4bc3/
K.regions.fasta  M.regions.fasta  Y.regions.fasta
```

```bash
cat work/3e/5ff788e6e2b394a6cf9e3932be4bc3/.command.log
Loading required package: ggplot2
Loading required package: ggseqlogo
Loading required package: readr
Error in fix.by(by.x, x) : 'by' must specify a uniquely valid column
Calls: ggseqlogo ... merge.default -> merge -> merge.data.frame -> fix.by
Execution halted
```

The other 19/20 seem to work.

**Comment by hoelzer** [comment]
(it's barcode13, for documentation)

**Comment by hoelzer** [comment]
Hm wait, starting it now a second time and more processes are failing in the plot_motifs step

**Comment by hoelzer** [comment]
Alright, the RAM increase seems to work now but I dont know why some motifs are failing?


[96/7d5808] process > mask_regions_degen_wf:minimap2_degen (1)  [100%] 20 of 20, cached: 20 ✔
[70/639da3] process > mask_regions_degen_wf:bedtools (14)       [100%] 20 of 20, cached: 20 ✔
[56/bb6e70] process > mask_regions_degen_wf:plasflow_degen (18) [100%] 20 of 20, cached: 20 ✔
[f0/ef294f] process > identify_logo_wf:count_positions (15)     [100%] 20 of 20, cached: 20 ✔
[75/a78f22] process > identify_logo_wf:extract_sequence (7)     [100%] 13 of 13, cached: 13 ✔
[3d/cf6340] process > identify_logo_wf:plot_motifs (12)         [100%] 13 of 13, cached: 5, failed: 8 ✔
[66/8b7772] process > identify_logo_wf:get_frequency (5)        [100%] 19 of 19, cached: 12, failed: 6, retries: 6 ✔
[6d/72402b] process > identify_logo_wf:plot_frequency           [100%] 1 of 1 ✔
Completed at: 08-Nov-2023 20:20:59
Duration    : 32m 52s
CPU hours   : 23.5 (86.2% cached, 5.2% failed)
Succeeded   : 2
Cached      : 110
Ignored     : 8
Failed      : 14

The error is ignored... but why does it fail?

**Comment by hoelzer** [comment]
btw `quay.io/biocontainers/plasflow:1.1.0--py35_0` now also works for me on the HPC (change in allowlist). In case you want to keep that instead of the nanozoo container. On the other hand, now all containers are nanozoo and have probably a similar base image which is nice for reducing storage.

**Comment by replikation** [comment]
Need to check if it's also cloud compatible. But then yes

**Comment by hoelzer** [comment]
The NZ one? Is for sure cloud compatible, or? ;)

So just to be clear

1) you have a quay container in master
2) I switched in this branch to nz container due to problems on restricted HPC
3) but our firewall now allows quay
4) so up to you if you want to stick with quay like in current master or use nz for all containers

Secondly, I still have several motif generations failing but the error is ignored. Is this intended? Maybe sometimes when the Consensus sequences are "perfect" you can simply not calculate a motif?

**Comment by maralohde** [comment]
> How do I interpret this plot again : )
@hoelzer The violin chart shows the ratio between two bases within the read data in ambiguous positions and indicates the base that is most frequently represented in the respective combination. We plotted the percentage share of each base per position. 

For example: We have a position masked with K, with a distribution of 30% G and 70% T. So we have 2 data points for this position, each shown in two separate violin plots under the IUPAC base K.

**Comment by maralohde** [comment]
> The NZ one? Is for sure cloud compatible, or? ;)
> 
> So just to be clear
> 
>     1. you have a quay container in master
> 
>     2. I switched in this branch to nz container due to problems on restricted HPC
> 
>     3. but our firewall now allows quay
> 
>     4. so up to you if you want to stick with quay like in current master or use nz for all containers
> 
>
> Secondly, I still have several motif generations failing but the error is ignored. Is this intended? Maybe sometimes when the Consensus sequences are "perfect" you can simply not calculate a motif?

Exactly, if there are no masked bases no motif can be generated and additionally we set the threshold as five masked bases for the plot. Accordingly, the plotting failed and was ignored so that the WF did not abort.

**Comment by hoelzer** [comment]
alright, great! Thanks for the explanations and anyway the tool ;) 

So one could even use it for filtering "correct" consensus genomes (in terms of nucleotide ambiguities) vs those that have biases (those will produce motifs).

**Comment by replikation** [comment]
do you have an idea how?

**Comment by hoelzer** [comment]
I mean, it should be simple. You already have a text file output of the number of ambiguous sites found in a consensus. And then you could just split the input FASTAs that are "problematic" in one folder and the ones that have no (or few) ambiguous sites into another (probably the ones that fail in the motif generation process). 

Maybe its not necessary because all the information is there already and users can also filter on their own ;)

**Pull request merged**
